  version: '3.9'
  services:
    db:
      image: postgres:14-alpine
      ports:
        - 5433:5432
      volumes:
        - ~/simple-bank/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=root
        - POSTGRES_DB=simple-bank